# step_timing_adaptation/lipm_state_generator.py

from __future__ import annotations

from dataclasses import dataclass
import math

import numpy as np


# ============================================================
# OUTPUT
# ============================================================

@dataclass(frozen=True)
class LIPMSample:

    position: np.ndarray
    velocity: np.ndarray
    acceleration: np.ndarray
    dcm: np.ndarray
    support_position: np.ndarray


# ============================================================
# POINT-FOOT LIPM
# ============================================================

class PointFootLIPM:
    """
    Exact horizontal LIPM state generator.

    Model:

        c_ddot = omega^2 * (c - u0)

    where:

        c  : horizontal CoM position
        u0 : current stance-foot CoP / ZMP

    During one support phase:

        u0 = constant

    At touchdown:

        u0(new) = uT

    where uT is the landing location selected by the
    adaptive step-location / step-timing planner.

    Horizontal propagation is analytical, not Euler.
    Vertical CoM height is constant.
    """

    def __init__(
        self,
        *,
        gravity: float,
        com_height: float,
        initial_position,
        initial_velocity,
        support_position,
    ) -> None:

        self.gravity = float(
            gravity
        )

        self.com_height = float(
            com_height
        )

        if self.gravity <= 0.0:

            raise ValueError(
                "gravity must be positive."
            )

        if self.com_height <= 0.0:

            raise ValueError(
                "com_height must be positive."
            )

        self.omega = math.sqrt(
            self.gravity
            /
            self.com_height
        )

        position = self._vector3(
            initial_position,
            "initial_position",
        )

        velocity = self._vector3(
            initial_velocity,
            "initial_velocity",
        )

        support = self._vector3(
            support_position,
            "support_position",
        )

        self._position_xy = (
            position[0:2].copy()
        )

        self._velocity_xy = (
            velocity[0:2].copy()
        )

        self._com_z = float(
            position[2]
        )

        self._support_position = (
            support.copy()
        )


    # ========================================================
    # SUPPORT SWITCH
    # ========================================================

    def set_support_position(
        self,
        support_position,
    ) -> None:

        """
        Switch point-foot support without changing CoM
        position or velocity.

        At touchdown:

            u0 <- uT
        """

        support = self._vector3(
            support_position,
            "support_position",
        )

        self._support_position = (
            support.copy()
        )


    # ========================================================
    # SYNTHETIC DCM DISTURBANCE
    # ========================================================

    def apply_dcm_disturbance(
        self,
        delta_dcm_x: float,
        delta_dcm_y: float,
    ) -> None:

        """
        Since:

            xi = c + c_dot / omega

        a desired instantaneous DCM change Delta xi is
        generated by:

            Delta c_dot = omega * Delta xi
        """

        delta = np.array(
            [
                float(
                    delta_dcm_x
                ),
                float(
                    delta_dcm_y
                ),
            ],
            dtype=float,
        )

        if not np.all(
            np.isfinite(
                delta
            )
        ):

            raise ValueError(
                "DCM disturbance must be finite."
            )

        self._velocity_xy += (
            self.omega
            *
            delta
        )


    # ========================================================
    # CURRENT SAMPLE
    # ========================================================

    def sample(
        self,
    ) -> LIPMSample:

        support_xy = (
            self._support_position[
                0:2
            ]
        )

        acceleration_xy = (
            self.omega**2
            *
            (
                self._position_xy
                -
                support_xy
            )
        )

        dcm = (
            self._position_xy
            +
            self._velocity_xy
            /
            self.omega
        )

        position = np.array(
            [
                self._position_xy[0],
                self._position_xy[1],
                self._com_z,
            ],
            dtype=float,
        )

        velocity = np.array(
            [
                self._velocity_xy[0],
                self._velocity_xy[1],
                0.0,
            ],
            dtype=float,
        )

        acceleration = np.array(
            [
                acceleration_xy[0],
                acceleration_xy[1],
                0.0,
            ],
            dtype=float,
        )

        return LIPMSample(
            position=(
                position
            ),

            velocity=(
                velocity
            ),

            acceleration=(
                acceleration
            ),

            dcm=(
                dcm.copy()
            ),

            support_position=(
                self._support_position.copy()
            ),
        )


    # ========================================================
    # EXACT PROPAGATION
    # ========================================================

    def advance(
        self,
        dt: float,
    ) -> LIPMSample:

        """
        Exact solution over dt for constant support u0:

            c(t+dt)
              = u0
              + (c-u0) cosh(omega dt)
              + v/omega sinh(omega dt)

            v(t+dt)
              = omega(c-u0) sinh(omega dt)
              + v cosh(omega dt)
        """

        dt = float(
            dt
        )

        if (
            not math.isfinite(dt)
            or
            dt <= 0.0
        ):

            raise ValueError(
                "dt must be positive and finite."
            )

        support_xy = (
            self._support_position[
                0:2
            ]
        )

        relative_position = (
            self._position_xy
            -
            support_xy
        )

        omega_dt = (
            self.omega
            *
            dt
        )

        ch = math.cosh(
            omega_dt
        )

        sh = math.sinh(
            omega_dt
        )

        new_position = (
            support_xy
            +
            relative_position
            *
            ch
            +
            self._velocity_xy
            /
            self.omega
            *
            sh
        )

        new_velocity = (
            self.omega
            *
            relative_position
            *
            sh
            +
            self._velocity_xy
            *
            ch
        )

        self._position_xy = (
            new_position
        )

        self._velocity_xy = (
            new_velocity
        )

        return self.sample()


    # ========================================================
    # VALIDATION
    # ========================================================

    @staticmethod
    def _vector3(
        value,
        name: str,
    ) -> np.ndarray:

        value = np.asarray(
            value,
            dtype=float,
        )

        if value.shape != (
            3,
        ):

            raise ValueError(
                f"{name} must have shape (3,)."
            )

        if not np.all(
            np.isfinite(
                value
            )
        ):

            raise ValueError(
                f"{name} must contain finite values."
            )

        return value