# lipm_mpc/zmp_visualization.py

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


# ============================================================
# VISUAL GEOMETRY
# ============================================================

from footstep_planning.walking_visualization import (
    add_sphere,
    draw_polyline,
)


# ============================================================
# CONFIGURATION
# ============================================================

@dataclass
class ZMPVisualizationConfig:
    """
    Visualization-only parameters.

    All actual values are supplied by run.py so this module
    contains no walking/MPC design parameters.
    """

    show_current: bool
    show_trail: bool
    show_preview: bool

    current_z: float
    trail_z: float
    preview_z: float

    current_radius: float
    preview_radius: float

    trail_width: float
    preview_width: float

    trail_min_distance: float
    trail_max_points: int

    preview_point_stride: int

    current_rgba: np.ndarray
    trail_rgba: np.ndarray
    preview_rgba: np.ndarray
    preview_line_rgba: np.ndarray


# ============================================================
# LIPM ZMP VISUALIZER
# ============================================================

class LIPMZMPVisualizer:
    """
    Visualization of the ZMP generated by the LIPM.

    LIPM relation:

        x_Z = x_G - h/g * ddot{x}_G
        y_Z = y_G - h/g * ddot{y}_G

    This is planner-side LIPM ZMP.

    It is NOT:
        - MuJoCo COP
        - contact-force ZMP
        - measured ground reaction COP

    The class manages:

        1. current LIPM ZMP
        2. historical ZMP trail
        3. future MPC ZMP preview
        4. drawing the ZMP after WalkingVisualizer
    """

    def __init__(
        self,
        config: ZMPVisualizationConfig,
        com_height: float,
        gravity: float,
    ) -> None:

        self.config = config

        self.com_height = float(
            com_height
        )

        self.gravity = float(
            gravity
        )

        self._validate_configuration()

        self.current_zmp_xy = None

        self.current_zmp_world = None

        self.trail = []

        self.preview_world = None


    # ========================================================
    # VALIDATION
    # ========================================================

    def _validate_configuration(
        self,
    ) -> None:

        if (
            not np.isfinite(
                self.com_height
            )
            or
            self.com_height <= 0.0
        ):

            raise ValueError(
                "com_height must be finite and positive."
            )

        if (
            not np.isfinite(
                self.gravity
            )
            or
            self.gravity <= 0.0
        ):

            raise ValueError(
                "gravity must be finite and positive."
            )

        cfg = self.config

        if cfg.current_radius <= 0.0:

            raise ValueError(
                "current_radius must be positive."
            )

        if cfg.preview_radius <= 0.0:

            raise ValueError(
                "preview_radius must be positive."
            )

        if cfg.trail_width <= 0.0:

            raise ValueError(
                "trail_width must be positive."
            )

        if cfg.preview_width <= 0.0:

            raise ValueError(
                "preview_width must be positive."
            )

        if cfg.trail_min_distance < 0.0:

            raise ValueError(
                "trail_min_distance cannot be negative."
            )

        if cfg.trail_max_points <= 0:

            raise ValueError(
                "trail_max_points must be positive."
            )

        if cfg.preview_point_stride <= 0:

            raise ValueError(
                "preview_point_stride must be positive."
            )

        for name in (
            "current_rgba",
            "trail_rgba",
            "preview_rgba",
            "preview_line_rgba",
        ):

            value = np.asarray(
                getattr(
                    cfg,
                    name,
                ),
                dtype=np.float32,
            )

            if value.shape != (
                4,
            ):

                raise ValueError(
                    f"{name} must have shape (4,)."
                )

            if not np.all(
                np.isfinite(
                    value
                )
            ):

                raise ValueError(
                    f"{name} must contain finite values."
                )

            setattr(
                cfg,
                name,
                value.copy(),
            )


    # ========================================================
    # BASIC LIPM ZMP
    # ========================================================

    def compute_zmp_xy(
        self,
        com_position,
        com_acceleration,
    ) -> np.ndarray:
        """
        Compute continuous LIPM ZMP from CoM position and
        acceleration.

        Parameters
        ----------
        com_position:
            [x_G, y_G, z_G]

        com_acceleration:
            [ddot{x}_G, ddot{y}_G, ddot{z}_G]

        Returns
        -------
        np.ndarray
            [x_Z, y_Z]
        """

        com_position = np.asarray(
            com_position,
            dtype=float,
        )

        com_acceleration = np.asarray(
            com_acceleration,
            dtype=float,
        )

        if com_position.shape != (
            3,
        ):

            raise ValueError(
                "com_position must have shape (3,)."
            )

        if com_acceleration.shape != (
            3,
        ):

            raise ValueError(
                "com_acceleration must have shape (3,)."
            )

        if not np.all(
            np.isfinite(
                com_position
            )
        ):

            raise ValueError(
                "com_position must contain finite values."
            )

        if not np.all(
            np.isfinite(
                com_acceleration
            )
        ):

            raise ValueError(
                "com_acceleration must contain finite values."
            )

        scale = (
            self.com_height
            /
            self.gravity
        )

        x_zmp = (
            com_position[0]
            -
            scale
            *
            com_acceleration[0]
        )

        y_zmp = (
            com_position[1]
            -
            scale
            *
            com_acceleration[1]
        )

        return np.array(
            [
                x_zmp,
                y_zmp,
            ],
            dtype=float,
        )


    # ========================================================
    # ZMP FROM LIPM STATES
    # ========================================================

    def compute_zmp_from_states(
        self,
        x_state,
        y_state,
    ) -> np.ndarray:
        """
        Compute ZMP from the two horizontal LIPM states:

            x_state = [x, dx, ddx]
            y_state = [y, dy, ddy]
        """

        x_state = np.asarray(
            x_state,
            dtype=float,
        )

        y_state = np.asarray(
            y_state,
            dtype=float,
        )

        if x_state.shape != (
            3,
        ):

            raise ValueError(
                "x_state must have shape (3,)."
            )

        if y_state.shape != (
            3,
        ):

            raise ValueError(
                "y_state must have shape (3,)."
            )

        scale = (
            self.com_height
            /
            self.gravity
        )

        return np.array(
            [
                x_state[0]
                -
                scale
                *
                x_state[2],

                y_state[0]
                -
                scale
                *
                y_state[2],
            ],
            dtype=float,
        )


    # ========================================================
    # WORLD POINT
    # ========================================================

    @staticmethod
    def _make_world_point(
        zmp_xy,
        z_height,
    ) -> np.ndarray:

        zmp_xy = np.asarray(
            zmp_xy,
            dtype=float,
        )

        if zmp_xy.shape != (
            2,
        ):

            raise ValueError(
                "zmp_xy must have shape (2,)."
            )

        return np.array(
            [
                zmp_xy[0],
                zmp_xy[1],
                float(
                    z_height
                ),
            ],
            dtype=float,
        )


    # ========================================================
    # INITIALIZATION
    # ========================================================

    def initialize_from_states(
        self,
        x_state,
        y_state,
    ) -> np.ndarray:

        zmp_xy = (
            self.compute_zmp_from_states(
                x_state,
                y_state,
            )
        )

        self.current_zmp_xy = (
            zmp_xy.copy()
        )

        self.current_zmp_world = (
            self._make_world_point(
                zmp_xy,
                self.config.current_z,
            )
        )

        self.trail = []

        self._append_trail_point(
            self.current_zmp_world
        )

        return (
            zmp_xy.copy()
        )


    # ========================================================
    # CURRENT CONTINUOUS ZMP
    # ========================================================

    def update_current(
        self,
        com_position,
        com_acceleration,
    ) -> np.ndarray:
        """
        Update the currently displayed LIPM ZMP.

        Normally called at the executor / IK rate.
        """

        zmp_xy = (
            self.compute_zmp_xy(
                com_position,
                com_acceleration,
            )
        )

        self.current_zmp_xy = (
            zmp_xy.copy()
        )

        self.current_zmp_world = (
            self._make_world_point(
                zmp_xy,
                self.config.current_z,
            )
        )

        self._append_trail_point(
            self.current_zmp_world
        )

        return (
            zmp_xy.copy()
        )


    # ========================================================
    # TRAIL
    # ========================================================

    def _append_trail_point(
        self,
        point,
    ) -> None:

        point = np.asarray(
            point,
            dtype=float,
        ).copy()

        if point.shape != (
            3,
        ):

            raise ValueError(
                "trail point must have shape (3,)."
            )

        point[2] = (
            self.config.trail_z
        )

        if len(
            self.trail
        ) == 0:

            self.trail.append(
                point
            )

        else:

            distance = float(
                np.linalg.norm(
                    point[0:2]
                    -
                    self.trail[-1][0:2]
                )
            )

            if (
                distance
                >=
                self.config.trail_min_distance
            ):

                self.trail.append(
                    point
                )

        if (
            len(
                self.trail
            )
            >
            self.config.trail_max_points
        ):

            remove_count = (
                len(
                    self.trail
                )
                -
                self.config.trail_max_points
            )

            del self.trail[
                0:remove_count
            ]


    # ========================================================
    # MPC PREVIEW
    # ========================================================

    def update_preview(
        self,
        x_result,
        y_result,
    ) -> np.ndarray:
        """
        Store future MPC ZMP points.

        MPC1DResult contains:

            x_result.zmp = [x_Z1 ... x_ZN]
            y_result.zmp = [y_Z1 ... y_ZN]

        The result is therefore exactly the ZMP sequence used
        by the MPC inequality constraints.
        """

        x_zmp = np.asarray(
            x_result.zmp,
            dtype=float,
        )

        y_zmp = np.asarray(
            y_result.zmp,
            dtype=float,
        )

        if x_zmp.ndim != 1:

            raise ValueError(
                "x_result.zmp must be 1D."
            )

        if y_zmp.ndim != 1:

            raise ValueError(
                "y_result.zmp must be 1D."
            )

        if x_zmp.shape != (
            y_zmp.shape
        ):

            raise ValueError(
                "X and Y ZMP previews must have equal length."
            )

        if len(
            x_zmp
        ) == 0:

            raise ValueError(
                "ZMP preview cannot be empty."
            )

        if not np.all(
            np.isfinite(
                x_zmp
            )
        ):

            raise ValueError(
                "X ZMP preview contains NaN/Inf."
            )

        if not np.all(
            np.isfinite(
                y_zmp
            )
        ):

            raise ValueError(
                "Y ZMP preview contains NaN/Inf."
            )

        preview = np.zeros(
            (
                len(
                    x_zmp
                ),
                3,
            ),
            dtype=float,
        )

        preview[:, 0] = (
            x_zmp
        )

        preview[:, 1] = (
            y_zmp
        )

        preview[:, 2] = (
            self.config.preview_z
        )

        self.preview_world = (
            preview
        )

        return (
            preview.copy()
        )


    # ========================================================
    # CLEAR PREVIEW
    # ========================================================

    def clear_preview(
        self,
    ) -> None:

        self.preview_world = (
            None
        )


    # ========================================================
    # DRAW ZMP OVERLAY
    # ========================================================

    def draw_overlay(
        self,
        viewer,
    ) -> None:
        """
        Draw only ZMP geometry.

        IMPORTANT:
        WalkingVisualizer.update() resets scene.ngeom to zero.
        Therefore this function must be called AFTER the
        standard WalkingVisualizer.
        """

        cfg = (
            self.config
        )

        with viewer.lock():

            scene = (
                viewer.user_scn
            )

            # =================================================
            # ZMP TRAIL
            # =================================================

            if (
                cfg.show_trail
                and
                len(
                    self.trail
                )
                >=
                2
            ):

                draw_polyline(
                    scene,
                    self.trail,
                    cfg.trail_width,
                    cfg.trail_rgba,
                )

            # =================================================
            # FUTURE MPC ZMP PREVIEW
            # =================================================

            if (
                cfg.show_preview
                and
                self.preview_world
                is not None
                and
                len(
                    self.preview_world
                )
                >
                0
            ):

                draw_polyline(
                    scene,
                    self.preview_world,
                    cfg.preview_width,
                    cfg.preview_line_rgba,
                )

                for k in range(
                    0,
                    len(
                        self.preview_world
                    ),
                    cfg.preview_point_stride,
                ):

                    add_sphere(
                        scene,
                        self.preview_world[k],
                        cfg.preview_radius,
                        cfg.preview_rgba,
                    )

            # =================================================
            # CURRENT LIPM ZMP
            # =================================================

            if (
                cfg.show_current
                and
                self.current_zmp_world
                is not None
            ):

                add_sphere(
                    scene,
                    self.current_zmp_world,
                    cfg.current_radius,
                    cfg.current_rgba,
                )

        viewer.sync()


    # ========================================================
    # COMPLETE VIEWER UPDATE
    # ========================================================

    def update_viewer(
        self,
        walking_visualizer,
        viewer,
        robot,
        state,
    ) -> None:
        """
        Standard visualization + LIPM ZMP overlay.

        Order matters:

            1. WalkingVisualizer
               -> clears and rebuilds user scene

            2. ZMP overlay
               -> appended afterwards
        """

        walking_visualizer.update(
            viewer,
            robot,
            state,
        )

        self.draw_overlay(
            viewer
        )